name: Gold Digger

permissions:
  contents: read
  issues: read
  pull-requests: write

on:
  milestone:
    types: [closed]

jobs:
  tag:
    name: Tag latest gold commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Release Notes
        uses: Decathlon/release-notes-generator-action@v3.1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILENAME: release
      - name: Create PR to gold
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr create -B gold -H main --title 'New deploy' --body-file release.md
